apiVersion: v1
kind: Service
metadata:
  labels:
    app: result-react
  name: result-react
spec:
  type: NodePort
  ports:
  - name: "result-react-service"
    port: 5002
    targetPort: 80
    nodePort: 31002
  selector:
    app: result-react
